/* Jenkinsfile (Declarative Pipeline) */
/* Requires the Docker Pipeline plugin */
pipeline {
    agent {
        kubernetes {
            defaultContainer 'jnlp'
        }
    }
    stages {
        stage('Initiate Pipeline') {
            steps {
                script {
                   def groovyScript = load "${env.WORKSPACE}/jenkins/1_Test/scripts/Jenkinsfile.groovy"
                }
            }
        }
    }
}
